# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 
      
      # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build 
          
      # Runs a set of commands using the runners shell
      - name: Git init
        run: |
          cd dist
          echo 'nightly.one-among.us' > CNAME
          git init
          git add -A
      
      - uses: EndBug/add-and-commit@v7
        with:
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: '[U] Deploy'
          branch: 'gh-pages'
